default: &default
    class: 'VizAspanFormer'
    ckpt: 'pretrained/aspanformer_outdoor.ckpt'
    match_threshold: 0.2
megadepth:
    <<: *default
scannet:
    <<: *default
hpatch:
    <<: *default
inloc:
    <<: *default
    imsize: 1024
    match_threshold: 0.3
aachen_v1.1:
    <<: *default
    imsize: 1024
    match_threshold: 0.3
